---

- name: stop services  # noqa no-changed-when
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
  failed_when: false
  with_items:
    - apache2
    - openproject

- name: run openproject backup  # noqa no-changed-when
  ansible.builtin.command: "{{ openproject_backup_command }}"

- name: start services  # noqa no-changed-when
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
  with_items:
    - openproject
    - apache2
