---

- name: install required packages
  ansible.builtin.apt:
    name: "{{ openproject_required_packages }}"

- name: openproject apt key
  ansible.builtin.apt_key:
    url: https://dl.packager.io/srv/opf/openproject/key
    state: present

- name: openproject apt repo
  ansible.builtin.apt_repository:
    repo: deb https://dl.packager.io/srv/deb/opf/openproject/stable/12/debian {{ ansible_distribution_major_version | default('11') }} main
    filename: openproject

- name: install openproject
  ansible.builtin.apt:
    name: openproject

- name: set openproject package on hold
  ansible.builtin.dpkg_selections:
    name: openproject
    selection: hold
  when: openproject_hold_package | bool

# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2 smartindent nu ft=yaml
