---

- name: install required packages
  ansible.builtin.apt:
    name: "{{ openproject_required_packages }}"

- name: openproject apt key
  ansible.builtin.apt_key:
    url: https://dl.packager.io/srv/opf/openproject/key
    state: present

- name: openproject apt repo
  ansible.builtin.apt_repository:
    repo: deb https://dl.packager.io/srv/deb/opf/openproject/stable/12/debian {{ ansible_distribution_major_version | default('11') }} main
    filename: openproject

- name: install openproject
  ansible.builtin.apt:
    name: openproject

- name: set openproject package on hold
  ansible.builtin.dpkg_selections:
    name: openproject
    selection: hold
  when: openproject_hold_package | bool

- name: copy ssl cert files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/ssl/certs/{{ item }}"
    mode: 0640
    group: root
    owner: root
  with_items:
    - "{{ openproject_filename_cert }}"
    - "{{ openproject_filename_key }}"
    - "{{ openproject_filename_ca }}"
  when:
    - item | length > 0
    - openproject_server.ssl == 'yes'

- name: deploy installer.dat
  ansible.builtin.template:
    src: installer.dat.j2
    dest: /etc/openproject/installer.dat
    backup: true
    mode: 0640
    owner: openproject
    group: openproject
  notify: openproject configure

- name: "openproject config:set"  # noqa no-changed-when
  ansible.builtin.command: "openproject config:set {{ item }}"
  notify: openproject restart
  with_items: "{{ openproject_configset }}"

# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2 smartindent nu ft=yaml
