---

- name: install required packages
  ansible.builtin.apt:
    name: "{{ openproject_required_packages }}"
    update_cache: true

- name: openproject apt key
  ansible.builtin.get_url:
    url: https://dl.packager.io/srv/opf/openproject/key
    dest: /usr/share/keyringspackager-io.asc
    mode: "0644"

- name: openproject apt repo for debian
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyringspackager-io.asc] https://dl.packager.io/srv/deb/opf/openproject/stable/{{ openproject_main_version }}/{{ ansible_distribution.lower() }} {{ ansible_distribution_major_version }} main
    filename: openproject
  when: ansible_distribution == 'Debian'

- name: openproject apt repo for ubuntu
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyringspackager-io.asc] https://dl.packager.io/srv/deb/opf/openproject/stable/{{ openproject_main_version }}/{{ ansible_distribution.lower() }} {{ ansible_distribution_version }} main
    filename: openproject
  when: ansible_distribution == 'Ubuntu'

- name: install openproject
  ansible.builtin.apt:
    name: openproject
    update_cache: true

- name: set openproject package on hold
  ansible.builtin.dpkg_selections:
    name: openproject
    selection: hold
  when: openproject_hold_package | bool

- name: copy ssl cert files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/ssl/certs/{{ item }}"
    mode: "0640"
    group: root
    owner: root
  notify:
    - openproject restart
    - apache2 restart
  diff: "{{ openproject_show_diff | default(false) | bool }}"
  with_items:
    - "{{ openproject_filename_cert }}"
    - "{{ openproject_filename_key }}"
    - "{{ openproject_filename_ca }}"
  when:
    - openproject_server.ssl == 'yes'
    - item | type_debug != 'NoneType'
    - item | length > 0

- name: deploy installer.dat
  ansible.builtin.template:
    src: installer.dat.j2
    dest: /etc/openproject/installer.dat-preconfig
    backup: true
    mode: "0640"
    owner: openproject
    group: openproject
  diff: "{{ openproject_show_diff | default(false) | bool }}"
  notify: openproject configure

- name: "openproject config:set"  # noqa no-changed-when
  ansible.builtin.command: "openproject config:set {{ item }}"
  notify: openproject restart
  with_items: "{{ openproject_configset }}"

# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2 smartindent nu ft=yaml
