---

- name: openproject configure
  ansible.builtin.command:
    cmd: openproject configure -f /etc/openproject/installer.dat-preconfig
    creates: /etc/openproject/installer.dat
  notify: openproject restart

- name: openproject restart
  ansible.builtin.service:
    name: openproject
    state: restarted

- name: apache2 restart
  ansible.builtin.service:
    name: apache2
    state: restarted
