---
name: ansible-lint
on:
  pull_request:
  push:
  schedule:
    - cron: "20 7 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'rls.openproject'
      - name: run ansible-lint
        uses: ansible/ansible-lint-action@v6.6.1
        with:
          path: '.'
